
cc_binary(
    name = "test_weak_sym",
    srcs = ["test_weak_sym.c", "weak.c"],
    copts = [
        "-g",
        "-Wall",
        "-Wextra",
    ],
)

cc_binary(
    name = "test_strong_sym",
    srcs = ["test_weak_sym.c", "strong.c"],
    copts = [
        "-g",
        "-Wall",
        "-Wextra",
    ],
)